const {requireUser}=require('./_auth');
const DEFAULT_URL='https://jijxmshpzcoalohlhhnb.supabase.co';
const DEFAULT_KEY='sb_publishable_pBnQxsVcunuxJrXLDNQnbQ_KWIbEyHy';
function cfg(){return{url:process.env.SUPABASE_URL||process.env.NEXT_PUBLIC_SUPABASE_URL||DEFAULT_URL,key:process.env.SUPABASE_PUBLISHABLE_KEY||process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY||DEFAULT_KEY}}
function norm(v=''){return String(v).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,' ').replace(/\s+/g,' ').trim()}
function similarity(a,b){const A=norm(a),B=norm(b);if(!A||!B)return 0;if(A===B)return 100;if(A.includes(B)||B.includes(A))return 88;const x=new Set(A.split(' ')),y=new Set(B.split(' '));const inter=[...x].filter(t=>y.has(t)).length;return inter/(new Set([...x,...y]).size||1)*80}
async function rest(req,path){const {url,key}=cfg();const auth=String(req.headers.authorization||'');const r=await fetch(`${url}/rest/v1/${path}`,{headers:{apikey:key,Authorization:auth,Accept:'application/json'}});if(!r.ok)throw new Error(`CACHE_${r.status}`);return r.json()}
function group(rows){const books=new Map();for(const r of rows){const b=r.bookmaker||'Bookmaker';if(!books.has(b))books.set(b,new Map());const ms=books.get(b),m=r.market_key||'market';if(!ms.has(m))ms.set(m,[]);ms.get(m).push({value:String(r.outcome_name||'')+(r.point!==null&&r.point!==undefined?` ${r.point}`:''),odd:Number(r.price)})}return[...books].map(([name,ms])=>({name,updated:'cache',markets:[...ms].map(([name,values])=>({name,values}))}))}
module.exports=async function handler(req,res){const user=await requireUser(req,res);if(!user)return;res.setHeader('Cache-Control','private, max-age=300, stale-while-revalidate=600');try{const league=String(req.query.leagueName||''),home=String(req.query.home||''),away=String(req.query.away||'');const from=new Date(Date.now()-3600000).toISOString(),to=new Date(Date.now()+96*3600000).toISOString();const fixtures=await rest(req,`football_fixtures_cache?select=*&kickoff_utc=gte.${encodeURIComponent(from)}&kickoff_utc=lte.${encodeURIComponent(to)}&order=kickoff_utc.asc`);let best=null,score=-1;for(const f of fixtures||[]){const direct=similarity(home,f.home_team_name)+similarity(away,f.away_team_name),reverse=similarity(home,f.away_team_name)+similarity(away,f.home_team_name),ls=league?similarity(league,f.league_name)*.35:0,sc=Math.max(direct,reverse)+ls;if(sc>score){best=f;score=sc}}if(!best||score<120)return res.status(200).json({ok:true,configured:true,source:'cache',bookmakers:[]});const rows=await rest(req,`football_odds_cache?select=*&fixture_id=eq.${Number(best.fixture_id)}`);return res.status(200).json({ok:true,configured:true,source:'cache',fixture_id:best.fixture_id,bookmakers:group(rows||[])})}catch{return res.status(200).json({ok:false,configured:true,source:'cache',bookmakers:[]})}};
